/* =============================================================================
 * catalog.js  —  THE PROJECT CATALOG (the curated "brain")
 * -----------------------------------------------------------------------------
 * WHY THIS FILE EXISTS
 * This is the reliable, offline, always-works recommendation engine. Every
 * project declares the CAPABILITIES it needs (see taxonomy.js for the token
 * vocabulary) — never a specific SKU — so any board/part you own that provides
 * those capabilities matches.
 *
 * HOW TO READ ONE PROJECT
 *   id          unique slug (used internally + for "more like this")
 *   title       shown on the card
 *   blurb       one-line "what it does"
 *   difficulty  Beginner | Intermediate | Advanced
 *   build时间   rough time ("~1 hour", "a weekend")
 *   requiredCaps  capabilities the project CANNOT run without
 *   optionalCaps  capabilities that make it better/complete but aren't required
 *   concepts    the ideas it teaches (shown as chips + drives the "WHY")
 *   why         the teaching blurb: WHAT you learn and WHY it matters
 *   steps       high-level wiring/build outline (enough to start, not full code)
 *   levelUp     one way to extend it once it works
 *   coolness   1–5 (ranking weight)
 *   learning   1–5 (ranking weight)
 *   tags       free-form grouping (used for "more like this")
 *
 * HOW TO ADD A PROJECT: copy a block, change id + caps + text. That's it.
 * The engine (engine.js) does the rest. No build step, no registration.
 *
 * Matching note: a project is "Buildable Now" when EVERY requiredCap is present
 * in your inventory. "Could've Been" = missing exactly 1–2 required caps.
 * ===========================================================================*/

(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.CATALOG = factory();
})(typeof self !== 'undefined' ? self : this, function () {

  const PROJECT_CATALOG = [

    // ============================ BEGINNER (board-agnostic where possible) ===
    {
      id: 'blink_button',
      title: 'Blink + Button',
      blurb: 'Light an LED that follows a button press.',
      difficulty: 'Beginner', buildTime: '~15 min',
      requiredCaps: ['mcu', 'button', 'led'],
      optionalCaps: ['resistor'],
      concepts: ['digital output', 'digital input', 'pull-up resistor'],
      why: 'The hello-world of hardware: you learn that an MCU pin can be an OUTPUT (drive an LED) or an INPUT (read a button), and why a resistor keeps the button pin from floating.',
      steps: [
        'Put the LED on a GPIO with a 220Ω resistor to ground.',
        'Wire the button between a GPIO and ground (use the MCU’s internal pull-up).',
        'In code: read the button; when pressed, turn the LED on.',
      ],
      levelUp: 'Add a second LED and make the button toggle between them.',
      coolness: 2, learning: 5, tags: ['gpio', 'basics'],
    },
    {
      id: 'pwm_dimmer',
      title: 'PWM LED Dimmer',
      blurb: 'Turn a knob and watch the LED brighten/dim smoothly.',
      difficulty: 'Beginner', buildTime: '~20 min',
      requiredCaps: ['mcu', 'led', 'potentiometer'],
      optionalCaps: ['resistor'],
      concepts: ['PWM', 'ADC', 'analog in → analog out'],
      why: 'Teaches PWM (faking "analog" brightness by blinking fast) and ADC (reading the pot’s position). This input→output mapping is the basis of almost every control project.',
      steps: [
        'Pot wiper → an ADC pin; the two ends go to 3.3V and GND.',
        'LED + 220Ω on a PWM-capable GPIO.',
        'Read the pot (0–4095), map it to 0–255, write it as PWM duty to the LED.',
      ],
      levelUp: 'Log the pot value over Serial and plot it to SEE the ADC curve.',
      coolness: 3, learning: 4, tags: ['pwm', 'analog'],
    },
    {
      id: 'motion_light',
      title: 'Motion-Activated Light',
      blurb: 'An LED (or lamp) switches on when something moves.',
      difficulty: 'Beginner', buildTime: '~30 min',
      requiredCaps: ['mcu', 'sensor-motion', 'led'],
      optionalCaps: ['relay'],
      concepts: ['digital input', 'state', 'relay for mains'],
      why: 'Builds on blink by adding a SENSOR as the trigger. If you add a relay you learn how a low-voltage MCU safely controls a real lamp.',
      steps: [
        'PIR OUT → a GPIO; power the PIR from 5V/GND.',
        'LED on a GPIO (or relay coil on a GPIO driving a lamp).',
        'When the PIR goes HIGH, turn the light on for a few seconds.',
      ],
      levelUp: 'Add a light sensor so it only triggers at night.',
      coolness: 3, learning: 4, tags: ['sensors', 'automation'],
    },
    {
      id: 'weather_station',
      title: 'Mini Weather Station',
      blurb: 'Reads temperature + humidity and shows them.',
      difficulty: 'Beginner', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'sensor-temp', 'sensor-humidity'],
      optionalCaps: ['display-i2c-oled', 'rtc'],
      concepts: ['I2C / 1-Wire', 'reading digital sensors', 'Serial Monitor'],
      why: 'Teaches how a digital sensor talks over a bus (I2C or 1-Wire) and how to turn raw numbers into something useful. Add the OLED and you learn a display library too.',
      steps: [
        'Connect the sensor (DHT22 data pin with a 10k pull-up; BME280 on I2C SDA/SCL).',
        'If you have an OLED, wire it on the same I2C bus.',
        'Flash the example, open Serial Monitor, watch the readings.',
        'Render temp/humidity on the OLED instead of Serial.',
      ],
      levelUp: 'Add an RTC + log a reading every 10 min to see trends.',
      coolness: 4, learning: 4, tags: ['sensors', 'display'],
    },
    {
      id: 'plant_monitor',
      title: 'Plant Moisture Monitor',
      blurb: 'Tells you when a plant needs water.',
      difficulty: 'Beginner', buildTime: '~30 min',
      requiredCaps: ['mcu', 'sensor-moisture'],
      optionalCaps: ['display-i2c-oled', 'buzzer'],
      concepts: ['ADC', 'thresholds', 'hysteresis'],
      why: 'A gentle first sensor project: read the soil probe as an analog value, pick a "dry" threshold, and act on it. Add a buzzer to get an alarm.',
      steps: [
        'Moisture module OUT → an ADC pin; power from 3.3V/GND.',
        'Print the reading; decide a threshold (e.g. < 300 = dry).',
        'Optional: beep the buzzer or show "WATER ME" on the OLED when dry.',
      ],
      levelUp: 'Average several readings so it doesn’t flicker around the threshold.',
      coolness: 3, learning: 4, tags: ['sensors', 'plants'],
    },
    {
      id: 'doorbell',
      title: 'Button Doorbell',
      blurb: 'Press a button, hear a chime.',
      difficulty: 'Beginner', buildTime: '~20 min',
      requiredCaps: ['mcu', 'button', 'buzzer'],
      optionalCaps: ['speaker'],
      concepts: ['input→output', 'tone()'],
      why: 'Shows the simplest complete loop: sense an event, make noise. Introduces tone() for pitched beeps.',
      steps: [
        'Button (pull-up) on one GPIO; buzzer on another.',
        'On press, play a two-note chime with tone().',
      ],
      levelUp: 'Play a short melody stored as an array of notes.',
      coolness: 2, learning: 3, tags: ['audio', 'basics'],
    },
    {
      id: 'distance_ranger',
      title: 'Distance Ranger',
      blurb: 'Measure how far away something is and show it.',
      difficulty: 'Beginner', buildTime: '~40 min',
      requiredCaps: ['mcu', 'sensor-distance'],
      optionalCaps: ['display-i2c-oled'],
      concepts: ['pulse timing', 'unit conversion', 'echo'],
      why: 'The HC-SR04 teaches you to measure TIME (send a ping, time the echo) and convert it to distance — a fundamental ranging technique.',
      steps: [
        'Trig→GPIO, Echo→GPIO; VCC 5V, GND common.',
        'Pulse Trig 10µs, measure Echo high-time, convert to cm.',
        'Print (and optionally show) the distance.',
      ],
      levelUp: 'Trigger an alarm when something enters a set range.',
      coolness: 3, learning: 4, tags: ['sensors', 'distance'],
    },
    {
      id: 'nightlight',
      title: 'Ambient Nightlight',
      blurb: 'An LED that brightens as the room darkens.',
      difficulty: 'Beginner', buildTime: '~30 min',
      requiredCaps: ['mcu', 'sensor-light', 'led'],
      optionalCaps: ['resistor'],
      concepts: ['analog read', 'inverse mapping', 'calibration'],
      why: 'Flips the dimmer around: the sensor drives the output. Teaches reading light as a number and inverting it (dark → bright).',
      steps: [
        'LDR as a voltage divider into an ADC pin.',
        'LED+220Ω on a PWM pin.',
        'Read light; map dark→high PWM, bright→low PWM.',
      ],
      levelUp: 'Add a pot to set the brightness "ceiling".',
      coolness: 2, learning: 3, tags: ['analog', 'light'],
    },
    {
      id: 'oled_hello',
      title: 'OLED Hello World',
      blurb: 'Print text and shapes on a tiny screen.',
      difficulty: 'Beginner', buildTime: '~30 min',
      requiredCaps: ['mcu', 'display-i2c-oled'],
      optionalCaps: ['sensor-temp'],
      concepts: ['I2C bus', 'display library', 'coordinates'],
      why: 'Your first real screen. You learn that the OLED sits on the I2C bus (just two wires) and that drawing is "put pixel/text at x,y".',
      steps: [
        'OLED VCC→3.3V, GND→GND, SDA→SDA, SCL→SCL.',
        'Load an OLED library, init at address 0x3C.',
        'Draw "Hello, Maker!" and a small box.',
      ],
      levelUp: 'Scroll the text across the screen.',
      coolness: 3, learning: 4, tags: ['display', 'i2c'],
    },
    {
      id: 'buzzer_melody',
      title: 'Buzzer Melody',
      blurb: 'Play a tune on a piezo buzzer.',
      difficulty: 'Beginner', buildTime: '~20 min',
      requiredCaps: ['mcu', 'buzzer'],
      optionalCaps: ['speaker'],
      concepts: ['tone()', 'frequency', 'arrays'],
      why: 'Sound is just frequency. You learn to map musical notes to Hz and play them in sequence from an array.',
      steps: [
        'Buzzer + → GPIO, − → GND.',
        'Store notes as {freq, ms} pairs.',
        'Loop: tone() each note for its duration.',
      ],
      levelUp: 'Read the notes from Serial so you can "type" a song.',
      coolness: 3, learning: 3, tags: ['audio'],
    },
    {
      id: 'servo_sweep',
      title: 'Servo Sweep',
      blurb: 'Sweep a servo arm back and forth.',
      difficulty: 'Beginner', buildTime: '~20 min',
      requiredCaps: ['mcu', 'servo'],
      optionalCaps: ['potentiometer'],
      concepts: ['PWM angles', 'servo protocol'],
      why: 'Servos want a specific PWM pulse width for each angle. You learn the 0–180° mapping and (with a pot) direct knob→angle control.',
      steps: [
        'Servo signal → PWM GPIO; power from 5V (or external if big).',
        'Loop angle 0→180→0, write with the servo library.',
        'Optional: map a pot to the angle for manual control.',
      ],
      levelUp: 'Add a second servo and make them move in sequence (a "wave").',
      coolness: 3, learning: 3, tags: ['motor', 'pwm'],
    },
    {
      id: 'pot_read',
      title: 'Read a Knob',
      blurb: 'Turn a pot and watch the number change.',
      difficulty: 'Beginner', buildTime: '~15 min',
      requiredCaps: ['mcu', 'potentiometer'],
      optionalCaps: ['led', 'display-i2c-oled'],
      concepts: ['ADC', 'Serial plotter'],
      why: 'The most direct way to "see" analog input: the pot sweeps 0–3.3V and the ADC reports 0–4095. Foundation for every analog control.',
      steps: [
        'Pot across 3.3V/GND, wiper→ADC pin.',
        'Print the raw value; watch it on the Serial Plotter.',
        'Optional: map it to LED brightness or OLED bar.',
      ],
      levelUp: 'Debounce it and use it to pick a menu item.',
      coolness: 2, learning: 4, tags: ['analog', 'basics'],
    },

    // ============================ INTERMEDIATE ===============================
    {
      id: 'wifi_clock',
      title: 'WiFi NTP Clock',
      blurb: 'A wall clock that sets itself over the internet.',
      difficulty: 'Intermediate', buildTime: '~1–2 hours',
      requiredCaps: ['mcu-wifi', 'rtc', 'display-i2c-oled'],
      optionalCaps: [],
      concepts: ['WiFi join', 'NTP', 'RTC', 'I2C'],
      why: 'Your first networked project: connect to WiFi, ask an NTP server for the time, and keep it ticking on a battery-backed RTC so it survives reboots. The OLED shows it.',
      steps: [
        'Wire OLED + DS3231 RTC on the I2C bus.',
        'Connect to your WiFi; fetch NTP time once.',
        'Write time to the RTC; each loop read RTC and draw HH:MM:SS.',
      ],
      levelUp: 'Add a buzzer alarm set from Serial.',
      coolness: 4, learning: 4, tags: ['wifi', 'clock', 'display'],
    },
    {
      id: 'wifi_weather_dash',
      title: 'WiFi Weather Dashboard',
      blurb: 'Pull live weather and show it on a screen.',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu-wifi', 'sensor-temp', 'sensor-humidity', 'display-i2c-oled'],
      optionalCaps: ['sensor-pressure'],
      concepts: ['HTTP client', 'JSON parsing', 'sensors'],
      why: 'Combines a sensor AND the internet: read your local sensor, fetch a forecast over HTTP, and parse JSON — the core skill of any "smart" gadget.',
      steps: [
        'Wire OLED + your temp/humidity sensor (I2C or 1-Wire).',
        'Join WiFi; GET a weather API (or a local sensor only).',
        'Parse the JSON; draw "Inside 22°/50%  Outside 18°/60%".',
      ],
      levelUp: 'Cache the forecast and only refresh every 10 min to save power.',
      coolness: 5, learning: 5, tags: ['wifi', 'sensors', 'display'],
    },
    {
      id: 'plant_monitor_display',
      title: 'Plant Monitor + Screen',
      blurb: 'A potted-plant dashboard with a readout.',
      difficulty: 'Intermediate', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'sensor-moisture', 'display-i2c-oled'],
      optionalCaps: ['buzzer', 'sensor-temp'],
      concepts: ['ADC', 'UI on a screen', 'states'],
      why: 'Upgrades the beginner moisture monitor with a proper display: you learn to lay out a tiny UI and show "DRY / OK / WET" states.',
      steps: [
        'Moisture probe → ADC; OLED on I2C.',
        'Map reading to a state; draw a bar + label.',
        'Optional: beep when DRY.',
      ],
      levelUp: 'Add a pump + relay to auto-water when dry.',
      coolness: 3, learning: 4, tags: ['sensors', 'plants', 'display'],
    },
    {
      id: 'rfid_door_lock',
      title: 'RFID Door Lock',
      blurb: 'A tag unlocks a relay-controlled latch.',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu', 'rfid', 'relay'],
      optionalCaps: ['buzzer'],
      concepts: ['SPI', 'RFID/UID', 'access control'],
      why: 'The RC522 speaks SPI. You learn to read a card’s UID, compare it to an allow-list, and trip a relay — the bones of any badge system.',
      steps: [
        'RC522 on SPI (SDA/SCK/MOSI/MISO/RST); relay on a GPIO.',
        'Read UID on tag-present; compare to an array of allowed UIDs.',
        'If allowed, pulse the relay (unlock) and beep OK.',
      ],
      levelUp: 'Store allowed UIDs in EEPROM so you can "enroll" new tags.',
      coolness: 5, learning: 4, tags: ['rfid', 'security', 'spi'],
    },
    {
      id: 'retro_snake',
      title: 'Retro Snake (OLED)',
      blurb: 'Play Snake on a tiny screen with buttons.',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu', 'display-i2c-oled', 'button'],
      optionalCaps: ['rotary-encoder'],
      concepts: ['game loop', 'arrays', 'input handling'],
      why: 'A real game teaches the loop: read input → update state → draw. Great practice with arrays (the snake body) and timing.',
      steps: [
        'OLED on I2C; one button per direction (or 4 buttons).',
        'Keep the snake as a list of x,y cells; move each tick.',
        'On eating food, grow; on self/wall hit, game over.',
      ],
      levelUp: 'Add a score on the screen + a "game over" buzzer.',
      coolness: 5, learning: 4, tags: ['game', 'display'],
    },
    {
      id: 'tft_dashboard',
      title: 'TFT Touch Dashboard',
      blurb: 'A rich GUI on a color touch screen (great on a CYD).',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu', 'display-spi-tft'],
      optionalCaps: ['sensor-temp', 'touch'],
      concepts: ['SPI TFT', 'colors/bitmaps', 'touch'],
      why: 'A color TFT (and especially the all-in-one CYD) unlocks phone-like UIs. You learn SPI screens, drawing primitives, and reading touch.',
      steps: [
        'TFT on SPI (CS/DC/RST per your board); CYD is pre-wired.',
        'Draw labels, bars, and a live sensor value.',
        'Optional: detect touch zones as buttons.',
      ],
      levelUp: 'Make a 2-screen UI you switch by touching a tab.',
      coolness: 5, learning: 4, tags: ['display', 'tft', 'cyd'],
    },
    {
      id: 'battery_node',
      title: 'Battery Sensor Node (deep sleep)',
      blurb: 'A temp node that runs for weeks on a cell.',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu', 'sensor-temp', 'battery-18650', 'charge-tp4056', 'power-boost'],
      optionalCaps: ['lora', 'rtc', 'display-i2c-oled'],
      concepts: ['deep sleep', 'power budgeting', 'boost converter'],
      why: 'The most important maker power lesson: a boost converter makes a steady 5V from a Li-ion cell, and deep-sleep drops current to microamps so it lasts for weeks, not hours.',
      steps: [
        '18650 → TP4056 (charge) → boost → 5V to the MCU.',
        'Read temp; optionally show/store it.',
        'Enter deep sleep; wake every N minutes via timer/RTC.',
      ],
      levelUp: 'Add LoRa to send the reading to a base station wirelessly.',
      coolness: 4, learning: 5, tags: ['power', 'sensors', 'battery'],
    },
    {
      id: 'lora_messenger',
      title: 'LoRa Messenger',
      blurb: 'Send text between two boards, km apart, no WiFi.',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu', 'lora'],
      optionalCaps: ['mcu-wifi', 'display-i2c-oled'],
      concepts: ['LoRa radio', 'SPI', 'peer-to-peer'],
      why: 'LoRa is long-range, low-power radio with no infrastructure. You learn to send/receive packets over SPI radios — the basis of off-grid sensor nets.',
      steps: [
        'SX1278 on SPI with an antenna; power from 3.3V.',
        'One board sends "ping", the other replies "pong".',
        'Optional: show messages on an OLED.',
      ],
      levelUp: 'Build a 3+ node mesh that relays messages.',
      coolness: 5, learning: 4, tags: ['lora', 'radio'],
    },
    {
      id: 'ble_temp',
      title: 'BLE Temp Notifier',
      blurb: 'Your phone gets a temperature alert over Bluetooth.',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu-ble', 'sensor-temp'],
      optionalCaps: ['display-i2c-oled', 'buzzer'],
      concepts: ['BLE', 'GATT notify', 'phone pairing'],
      why: 'Teaches Bluetooth Low Energy: you expose the temperature as a BLE characteristic your phone can read/notify — no app store needed, just a BLE scanner.',
      steps: [
        'Wire your temp sensor.',
        'Start a BLE server with a "temperature" characteristic.',
        'Notify on change; watch it on a phone BLE app.',
      ],
      levelUp: 'Add a "too hot" threshold that also beeps locally.',
      coolness: 4, learning: 4, tags: ['ble', 'sensors', 'phone'],
    },
    {
      id: 'stepper_controller',
      title: 'Stepper Controller',
      blurb: 'Position a stepper precisely (e.g. a dial or stage).',
      difficulty: 'Intermediate', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'stepper', 'motor-driver'],
      optionalCaps: ['button', 'rotary-encoder'],
      concepts: ['step sequencing', 'driver boards', 'position'],
      why: 'Unlike a servo, a stepper moves in exact steps. You learn the coil-firing sequence (via ULN2003/A4988) and absolute positioning.',
      steps: [
        '28BYJ-48 → ULN2003 → GPIOs (or A4988 for bigger motors).',
        'Step forward/back a set count per button press.',
        'Optional: encoder sets the target position.',
      ],
      levelUp: 'Add limit switches so it "homes" on power-up.',
      coolness: 3, learning: 4, tags: ['motor', 'stepper'],
    },
    {
      id: 'dc_motor_pwm',
      title: 'DC Motor Speed Control',
      blurb: 'Spin a DC motor at a knob-controlled speed.',
      difficulty: 'Intermediate', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'dc-motor', 'motor-driver'],
      optionalCaps: ['potentiometer'],
      concepts: ['H-bridge', 'PWM direction/speed', 'flyback'],
      why: 'A DC motor needs an H-bridge (L298N) to reverse and a PWM signal for speed. You learn both, plus why the driver is separate from the MCU.',
      steps: [
        'Motor → L298N outputs; L298N inputs → PWM GPIOs.',
        'Pot → ADC sets speed; a button picks direction.',
        'Write PWM duty to spin; flip pins to reverse.',
      ],
      levelUp: 'Add a tachometer (encoder) for closed-loop speed.',
      coolness: 3, learning: 4, tags: ['motor', 'pwm'],
    },
    {
      id: 'rotary_menu',
      title: 'Rotary Menu (OLED)',
      blurb: 'Scroll a menu and pick items with a knob.',
      difficulty: 'Intermediate', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'rotary-encoder', 'display-i2c-oled'],
      optionalCaps: [],
      concepts: ['interrupts', 'quadrature', 'menus'],
      why: 'Rotary encoders output two offset signals (quadrature). You learn to decode direction with interrupts and build a navigable UI — the classic "knob UI".',
      steps: [
        'Encoder A/B → two interrupt GPIOs; OLED on I2C.',
        'On each tick, move the highlighted menu row up/down.',
        'Press the encoder to "select".',
      ],
      levelUp: 'Make selecting an item launch a different project.',
      coolness: 4, learning: 4, tags: ['display', 'ui', 'encoder'],
    },
    {
      id: 'gas_alarm',
      title: 'Gas / Smoke Alarm',
      blurb: 'Beeps when smoke or gas rises.',
      difficulty: 'Intermediate', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'sensor-gas', 'buzzer'],
      optionalCaps: ['led', 'display-i2c-oled'],
      concepts: ['analog threshold', 'warm-up', 'alarm state'],
      why: 'MQ-2 needs a warm-up and gives an analog reading. You learn thresholds, a "latching" alarm state, and why sensors need to settle.',
      steps: [
        'MQ-2 AO → ADC; allow ~20s warm-up on first power.',
        'If reading > threshold, sound the buzzer + light an LED.',
        'Optional: show the ppm-ish value on the OLED.',
      ],
      levelUp: 'Add WiFi to push a phone alert.',
      coolness: 4, learning: 3, tags: ['sensors', 'safety', 'audio'],
    },
    {
      id: 'led_matrix_scroller',
      title: 'LED Matrix Scroller',
      blurb: 'Scroll a message across a dot-matrix.',
      difficulty: 'Intermediate', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'display-ledmatrix'],
      optionalCaps: ['rtc'],
      concepts: ['SPI', 'font bitmaps', 'animation'],
      why: 'A MAX7219 matrix teaches you to push pixel data over SPI and animate by shifting a font bitmap — the basis of any LED sign.',
      steps: [
        'Matrix on SPI (CLK/DIN/CS).',
        'Load a font; render a string as columns.',
        'Shift the columns left each tick to scroll.',
      ],
      levelUp: 'Show the time scrolling (needs an RTC).',
      coolness: 4, learning: 3, tags: ['display', 'led'],
    },
    {
      id: 'smart_relay_timer',
      title: 'Smart Relay Timer',
      blurb: 'Switch a load on a schedule, no cloud.',
      difficulty: 'Intermediate', buildTime: '~1 hour',
      requiredCaps: ['mcu', 'relay', 'rtc'],
      optionalCaps: ['mcu-wifi', 'button'],
      concepts: ['scheduling', 'RTC', 'mains safety'],
      why: 'Combines an RTC with a relay so a lamp/fan turns on at set times — fully local. Teaches time math + safely switching mains via the relay.',
      steps: [
        'DS3231 RTC on I2C; relay coil on a GPIO (isolated).',
        'Each loop, compare RTC time to ON/OFF times.',
        'Drive the relay accordingly.',
      ],
      levelUp: 'Add WiFi to fetch sunrise/sunset times for auto on/off.',
      coolness: 3, learning: 4, tags: ['automation', 'relay', 'clock'],
    },
    {
      id: 'eink_frame',
      title: 'E-ink Info Frame',
      blurb: 'A low-power wall frame that updates now and then.',
      difficulty: 'Intermediate', buildTime: '~2 hours',
      requiredCaps: ['mcu', 'display-eink'],
      optionalCaps: ['mcu-wifi', 'sensor-temp'],
      concepts: ['e-ink refresh', 'low power', 'bitmaps'],
      why: 'E-ink only uses power when it changes. You learn the slow-but-clean refresh and why it’s perfect for battery wall displays.',
      steps: [
        'E-ink on SPI (BUSY/RES/DC/CS per your panel).',
        'Draw text/a small bitmap.',
        'Optional: fetch a reading over WiFi and refresh hourly.',
      ],
      levelUp: 'Show a daily weather "card" that refreshes once a morning.',
      coolness: 4, learning: 4, tags: ['display', 'eink', 'power'],
    },

    // ============================ ADVANCED ===================================
    {
      id: 'weather_lora_remote',
      title: 'Remote Weather Station (LoRa)',
      blurb: 'A sensor node beams readings to a base display.',
      difficulty: 'Advanced', buildTime: 'a weekend',
      requiredCaps: ['mcu', 'sensor-temp', 'sensor-humidity', 'lora'],
      optionalCaps: ['display-i2c-oled', 'rtc', 'battery-18650'],
      concepts: ['remote sensing', 'LoRa packets', 'base+node'],
      why: 'Stitches sensors + LoRa + (optional) battery into a real two-part system: a node that measures and a base that receives and shows. The leap from "one board" to "a network".',
      steps: [
        'Node: temp/humidity sensor + LoRa; send a packet every minute.',
        'Base: another LoRa that receives and prints/show on OLED.',
        'Optional: run the node on a 18650 + deep sleep.',
      ],
      levelUp: 'Add a second node on a different address (multi-sensor net).',
      coolness: 5, learning: 5, tags: ['lora', 'sensors', 'network'],
    },
    {
      id: 'ble_gamepad',
      title: 'BLE Game Controller',
      blurb: 'A wireless controller your phone/computer sees as HID.',
      difficulty: 'Advanced', buildTime: 'a weekend',
      requiredCaps: ['mcu-ble', 'button', 'rotary-encoder'],
      optionalCaps: ['display-i2c-oled'],
      concepts: ['BLE HID', 'input mapping', 'profiles'],
      why: 'Goes beyond notify: you emulate a real HID device over BLE so a phone/PC treats your buttons+knob as a gamepad. Deep dive into BLE profiles.',
      steps: [
        'Buttons + encoder → GPIOs; start a BLE HID profile.',
        'Map button presses to HID key/axis reports.',
        'Pair from a phone and use it in a game.',
      ],
      levelUp: 'Add vibration/LED feedback on button press.',
      coolness: 5, learning: 4, tags: ['ble', 'game', 'input'],
    },
    {
      id: 'security_system',
      title: 'Multi-Sensor Security System',
      blurb: 'Motion + RFID arm/disarm with a loud alarm.',
      difficulty: 'Advanced', buildTime: 'a weekend',
      requiredCaps: ['mcu', 'sensor-motion', 'rfid', 'buzzer'],
      optionalCaps: ['relay', 'mcu-wifi'],
      concepts: ['state machine', 'multi-sensor', 'arm/disarm'],
      why: 'The capstone combo: a state machine (DISARMED → ARMED → ALARM), an RFID "key" to arm/disarm, motion to trigger, and a buzzer alarm. Real system design.',
      steps: [
        'PIR + RC522 + buzzer wired; RTC optional for logs.',
        'Swipe correct tag → ARM; wrong tag ignored.',
        'When ARMED and PIR trips → sound alarm; correct tag → DISARM.',
      ],
      levelUp: 'Add WiFi to send "intrusion" to your phone with a timestamp.',
      coolness: 5, learning: 5, tags: ['security', 'rfid', 'state-machine'],
    },
  ];

  return { PROJECT_CATALOG };
});
