#!/usr/bin/env python3
"""build_sketch_data.py — turn sketches/<id>/<id>.ino into js/sketches-data.js.

Reads every .ino under sketches/, grabs the ino source, and emits:
  window.SKETCHES_DATA = { "<id>": { lang: "cpp", source: "..." }, ... }
The catalog detail view (detail.js) loads this and renders a copy-paste block.

Why a generated file? The sketches are the source of truth (they get compile-checked in
CI via tools/compile_all.sh). Generating the data keeps the web app in sync with the
actual verifiable .ino files without hand-copying.
"""
import os, re, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKETCHES = os.path.join(ROOT, "sketches")
OUT = os.path.join(ROOT, "js", "sketches-data.js")

data = {}
for pid in sorted(os.listdir(SKETCHES)):
    d = os.path.join(SKETCHES, pid)
    ino = os.path.join(d, f"{pid}.ino")
    if not os.path.isfile(ino) or pid == "_ref":
        continue
    with open(ino, encoding="utf-8") as f:
        src = f.read()
    data[pid] = {"lang": "cpp", "source": src}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/build_sketch_data.py — do not edit by hand.\n")
    f.write("// Regenerate after changing sketches/ :  python3 tools/build_sketch_data.py\n")
    f.write("window.SKETCHES_DATA = ")
    f.write(json.dumps(data, ensure_ascii=False, indent=2))
    f.write(";\n")

print(f"Wrote {len(data)} sketches to js/sketches-data.js")
